Paggio.html do |_|
  _.script type: "text/javascript", src: "script.js"
  _.link rel: "stylesheet", href: "style.css"
  _.link rel: 'icon', type: 'image/x-icon', href: 'favicon.ico'
  _.img.justicar(src: '/justicar.png', alt: 'Justicar', height: '400px')
  _.h1 { "Hello world from Justicar" }
  _.hr
  _.h2.paggio do
    'Hello world from Paggio!'
  end
  _.p.paggio do
    "This part was generated by Paggio in HTML :)"
  end
  _.div do
    event_card('Camping in the Wild',
               'Choose: Destroy 1 Water and 1 Meal OR All players take 2 damage',
               'wd_t_02.PNG')
  end
end
