require 'opal'
require 'native'
require 'promise'
require 'browser/setup/full'

$document.ready do
  DOM do
    h2.opal do
      "Hello World from Opal!"
    end
    p.opal {"This part was generated by Opal from Javascript (:"}
    h2.articles do
      "Here is some articles that were generated using the processing system:"
    end
    p.articles do 
      a(href: '/articles').articles { "Articles" }
    end
  end.append_to($document.body)
end
